### ISSUE TITLE
How to enable logging

### ISSUE THREAD

**Issue by terrisgit** [jtgasper3/docker-shibboleth-idp#10]
/opt/shibboleth-idp/logs is empty yet conf/logback.xml "out of the box" specifies INFO for the logs I'm interested in.

Of course, I see files in /opt/iam-jetty-base/logs but they are for Jetty instead of Shibboleth idP.

Has anyone been able to get files to appear in /opt/shibboleth-idp/logs ?

Thank you

**Comment by terrisgit** [comment]
I was having a directory permission problems, since the user 'jetty' is running Shibboleth idP rather than 'root.' See also: http://stackoverflow.com/questions/23544282/what-is-the-best-way-to-manage-permissions-for-docker-shared-volumes

(1) On your Docker host, create a user and group both named jetty both with GID/UID = 1000

(2) mkdir -p ~/shibboleth-idp/logs

(3) In the 'docker run' command, add:

-v ~/shibboleth-idp/logs:/opt/shibboleth-idp/logs

Then the logs will be in ~/docker/shibboleth-idp on the Docker host. No need to change any config files.

(4) For every local directory (local to the Docker host) referenced in the -v options in your "docker run" command, run 'chown' on your Docker host:

chown -R jetty:jetty dirname

**Comment by terrisgit** [comment]
Perhaps update readme?

**Comment by terrisgit** [comment]
See also https://github.com/docker/docker/issues/7198

**Comment by jtgasper3** [comment]
@terrisgit, thanks for the report. I'll look into the details that you've posted over the coming days.

Thanks.

**Comment by terrisgit** [comment]
I eventually also had permission issues with files in /opt/iam-jetty-base/conf . They are owned by root but user 'jetty' needs to read them. Some files had permissions 660 instead of 664. I'm not sure how that happened. I was able to troubleshoot this only after my experience with the log files. I changed run-shibboleth.sh to run chown -R jetty:jetty on /opt/iam-user-base and /opt/shibboleth-idp

**Comment by jtgasper3** [comment]
I just merged in changes for 3.1.2. Now that this is current, I'll get your changes in place.

**Comment by jtgasper3** [comment]
The change I made tonight seems to produce logs in both locations: the IDP home and Jetty base.
