### ISSUE TITLE
Jetty 9.3

### ISSUE THREAD

**Issue by dev-guy** [jtgasper3/docker-shibboleth-idp#13]
I am working on upgrading both Shibboleth idP (to 3.1.2) and Jetty versions (to 9.3). There has been a lot of activity recently for Shibboleth idP running on Jetty 9.3:

https://wiki.shibboleth.net/confluence/display/IDP30/Jetty93

If I discover anything specific to this git repository, I'll post it here.

**Comment by jtgasper3** [comment]
Good timing. Yesterday I updated the Dockerfile to pull in Java 8, Jetty 9.3 and IdP 3.1.2. I didn't have time to validate any of the configs though, so I didn't publish my changes yet.

Also @dev-guy, I just want to give you a heads up in case it is of concern to you. I plan to move the ongoing work on this project to Unicon (my employer)'s Github repo. Unicon's IAM team will be able to work on it as well and that means hopefully better long term support.

**Comment by jschilperoord** [comment]
I was trying to get this working myself(Java 8 and Jetty 9.3). No luck so far. When I can start testing I will post my findings here.

**Comment by dev-guy** [comment]
@jtgasper3, not an issue. Thanks for your hard work and genius!

**Comment by jtgasper3** [comment]
I've pushed a new commit that incorporates Jetty 9.3.2, Java 8u60, and IdP 3.1.2. It's tagged as a beta: https://github.com/jtgasper3/docker-shibboleth-idp/tree/3.1.2-beta

Feel free to pull it and run it through its paces.  Front channel (443) and backchannel (8443) both respond as expected (showing the metadata from `/idp/shibboleth` and 8443 asking for a client-side cert), but I haven't connected it to an authn source and an SP. 

Please let me know how it works for you.

**Comment by jschilperoord** [comment]
Thanks for your great work on this @jtgasper3 :-)

**Comment by jschilperoord** [comment]
We didn't encounter any issues with the 3.1.2 branch image. FYI

**Comment by jtgasper3** [comment]
Thanks for the report. I'm going to merge.
