### ISSUE TITLE
Latest docker build doesn't start

### ISSUE THREAD

**Issue by jschilperoord** [jtgasper3/docker-shibboleth-idp#21]
I get the following error while starting the docker image with the latest tag:
- export JAVA_HOME=/opt/jre1.8.0_60
- JAVA_HOME=/opt/jre1.8.0_60
- export JETTY_HOME=/opt/jetty/
- JETTY_HOME=/opt/jetty/
- export JETTY_BASE=/opt/iam-jetty-base/
- JETTY_BASE=/opt/iam-jetty-base/
- export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/jre1.8.0_60/bin:/opt/container-scripts:/opt/jre1.8.0_60/bin
- PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/jre1.8.0_60/bin:/opt/container-scripts:/opt/jre1.8.0_60/bin
- sed -i 's/^-Xmx.*$/-Xmx512m/g' /opt/iam-jetty-base/start.ini
- /etc/init.d/jetty run
  /etc/init.d/jetty: line 326: which: command not found
  Cannot find a Java JDK. Please set either set JAVA or put java (>=1.5) in your PATH.

**Comment by jtgasper3** [comment]
Hi there,

I can take a look but don't plan on spending too much time on this project any more...  at least not here,  I've moved the work to https://hub.docker.com/r/unicon/shibboleth-idp/ / https://github.com/Unicon/shibboleth-idp-dockerized/, which is my company's repo where it will live on, be supported by my team, and hopefully become the defacto standard for the IdP's base image.

**Comment by jtgasper3** [comment]
I should add that you can see a fully working example of this Unicon image working at https://github.com/UniconLabs/dockerized-idp-testbed.

**Comment by jschilperoord** [comment]
@jtgasper3 Thanks for the update. I created a pull request for the fix. Its best to use the images you mentioned as a base then ?

**Comment by jtgasper3** [comment]
Thanks @jschilperoord. 

It's up to you how you do it. If you trust Unicon and Docker Hub, I'd just use what's published as a base, otherwise you can clone and build from the source. As for runtime, I'd still recommend using either as a base and either add in your own credentials or mounting them in... You can still use the base as an appliance, but its not really the Docker way.
