### ISSUE TITLE
Need to assign pseudo terminal for reset-idp.sh

### ISSUE THREAD

**Issue by fergusg** [jtgasper3/docker-shibboleth-idp#7]
In the README, need "-t" option, so password can be read from STDIN

```
docker exec -it idp-test reset-idp.sh
```

**Comment by jtgasper3** [comment]
You are absolutely right... Funny thing is I never type "-i" with out the "t" normally. That's been fixed in the master line. I'll catch the other git branches/docker tags the next time Java or Jetty get patched. 

Thanks for pointing that out.
