### ISSUE TITLE
keystore not found

### ISSUE THREAD

**Issue by terrisgit** [jtgasper3/docker-shibboleth-idp#8]
Hello,

Thanks for a wonderful tool! 

I am having a little trouble. When I run this:

docker build --tag="org_id/shibboleth-idp" github.com/jtgasper3/docker-shibboleth-idp

I get the following error.

((Was keystore renamed to keystore.pkf by the Jetty team? - see http://git.eclipse.org/c/jetty/org.eclipse.jetty.project.git/plain/jetty-server/src/main/config/etc - It looks like the URL needs to be changed to http://git.eclipse.org/c/jetty/org.eclipse.jetty.project.git/tree/jetty-server/src/main/config/etc/keystore?h=jetty-9.2.x))

DOWNLOAD: http://git.eclipse.org/c/jetty/org.eclipse.jetty.project.git/plain/jetty-server/src/main/config/etc/keystore to etc/keystore
WARNING: ERROR: processing DownloadArg [uri=http://git.eclipse.org/c/jetty/org.eclipse.jetty.project.git/plain/jetty-server/src/main/config/etc/keystore, location=etc/keystore]
java.io.FileNotFoundException: http://git.eclipse.org/c/jetty/org.eclipse.jetty.project.git/plain/jetty-server/src/main/config/etc/keystore
java.io.FileNotFoundException: http://git.eclipse.org/c/jetty/org.eclipse.jetty.project.git/plain/jetty-server/src/main/config/etc/keystore
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
    at java.net.URL.openStream(Unknown Source)
    at org.eclipse.jetty.start.Main.initFile(Main.java:203)
    at org.eclipse.jetty.start.Main.buildIni(Main.java:517)
    at org.eclipse.jetty.start.Main.buildIni(Main.java:550)
    at org.eclipse.jetty.start.Main.start(Main.java:707)
    at org.eclipse.jetty.start.Main.main(Main.java:112)

Usage: java -jar start.jar [options] [properties] [configs]
       java -jar start.jar --help  # for more information
INFO[0073] The command [/bin/sh -c set -x;     jetty_version=9.2.10.v20150310;   ... returned a non-zero code: 1

**Comment by jtgasper3** [comment]
Hi @terrisgit,

We can all thank Jetty for hosting config bits that are used by their app running in the same repo that they host dev code in.  Here's what's going on.

When calling:

```
$JRE_HOME/bin/java -jar ../jetty/start.jar --add-to-startd=http,https,deploy,ext,annotations,jstl,logging,setuid \
```

The `https` part, I'm assuming, pulls a keystore from their git repo. In this commit http://git.eclipse.org/c/jetty/org.eclipse.jetty.project.git/commit/?id=29393ace68bf08acaa24cbc539d1ca10a36a6ce7, they remove the file. Wasn't that nice of them? I've not check to see if this was reported as a bug or not.

I haven't decided how to fix this, but I see the following options:
1. Wait for the next release which will hopefully fix it.
2. Remove the offending item from add-to-startd and manually create the assets that it sets up.

**Comment by jtgasper3** [comment]
A bug was posted to Jetty: https://bugs.eclipse.org/bugs/show_bug.cgi?id=466634

**Comment by terrisgit** [comment]
Wow! Thanks for the quick response! I would have fixed it myself but I eventually found out that it wasn't in your files.

**Comment by jtgasper3** [comment]
This was resolved by the Jetty project. I've confirmed that the automated builds on the Docker Hub built properly.
