### ISSUE TITLE
Unresponsive after reset_idp.sh - Exception in thread "main" java.io.FileNotFoundException: /opt/shibboleth-idp/credentials/idp-backchannel.jks (No such file or directory)

### ISSUE THREAD

**Issue by dev-guy** [jtgasper3/docker-shibboleth-idp#9]
# A note on the image name

If you follow the build instructions, the image name starts with org_id, not jtgasper3. This is just a small documentation bug. Here's how I started it:

docker run -dP --name="idp-test" -v ~/docker/shib-config:/external-mount org_id/shibboleth-idp
# Docker VM's IP address

I am using Kitematic (OSX). In order to determine the IP address, I had to get the container to expose at least port 80 (so the 'view' button would work). The docker run command using -P didn't do this. So I deleted the container and started a new one.

docker run -d -p 80:80 -p 443:443 --name="idp-test" -v ~/docker/shib-config:/external-mount org_id/shibboleth-idp

If you're using boot2docker, run "boot2docker ip" to get the IP address.
# https://docker_vm_ip_address/idp

Using localhost doesn't work. Must use ip address, at least on OSX.

You'll get something like:

Our Identity Provider
No services are available at this location.
# Then I refreshed the Shibboleth idP config

docker exec -it idp-test reset-idp.sh

That's when things started going south.
# docker restart idp-test
# https://docker_vm_ip_address/idp

No response (timed out)
# docker exec -it idp-test bash

In a log file under /opt/iam-jetty-base/logs, I see

Exception in thread "main" java.io.FileNotFoundException: /opt/shibboleth-idp/credentials/idp-backchannel.jks (No such file or directory)

The file is actually named idp-backchannel.p12

I can modify the files on my own but I thought others might run into this.

**Comment by dev-guy** [comment]
I am still working out how to get Shibboleth to work with a PKCS file. I don't need the SOAP connector so ideally I would like to turn it off.

**Comment by dev-guy** [comment]
Here's how to turn it off: 

Modify /opt/iam-jetty-base/modules/shibboleth.mod

Comment out the line:

etc/jetty-shibboleth.xml

**Comment by jtgasper3** [comment]
@dev-guy, thanks for the thorough reporting. I've been swapped with my daily job and hadn't had time to play with the image, so I'll be getting it back up to snuff shortly. I've work on repo'ing the problem and testing your suggestions.

**Comment by jtgasper3** [comment]
This was related to a workaround I used on older versions. This should be fixed with the 3.1.2 release (see https://github.com/jtgasper3/docker-shibboleth-idp/tree/3.1.2-beta).

I started a new instance; ran `reset-idp.sh`, then ran `docker stop` and `docker start`. The instance came up fine.
